version: '3.8'
services:
  db:
    image: postgres:14
    ports:
      - "${DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - quiz-network
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_DATE: ${DATE:-$(date +%Y-%m-%d)}
    image: quiz-app-backend:1.0.0
    ports:
      - "${APP_PORT:-80}:80"
      - "${API_PORT:-8080}:8080"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      RUST_LOG: ${RUST_LOG}
      JWT_SECRET: ${JWT_SECRET}
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      SKIP_DB_INIT: true
    entrypoint: ["/bin/sh", "/app/backend/wait-for-it.sh", "db:5432", "--timeout=60", "--", "./backend/quiz-app-backend"]
    volumes:
      - ./quiz-app-frontend:/app/frontend
      - ./quiz-app-backend:/app/backend
      - cargo-cache:/usr/local/cargo/registry
      - frontend-node-modules:/app/quiz-app-frontend/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quiz-network
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    restart: unless-stopped

  endpoint-tester:
    build:
      context: .
      target: endpoint-tester
    image: quiz-app-endpoint-tests
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/quiz_app_test
      SQLX_OFFLINE: false
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    restart: unless-stopped

volumes:
  cargo-cache:
  postgres_data:
  frontend-node-modules:

networks:
  quiz-network:
    driver: bridge